In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import * 
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data")

In [4]:
df.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [5]:
df.shape


(624, 5)

In [6]:
x=df.drop(["B"],axis=1)


In [7]:
y=df["B"]


In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=20)


In [9]:
model = DecisionTreeClassifier(random_state=3,max_features=1)


In [10]:
model.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=1, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=3, splitter='best')

In [11]:
pred = model.predict(X_test)


In [12]:
accuracy_score(Y_test,pred)


0.8191489361702128

In [13]:
print("Classification Report:\n")
print(classification_report(Y_test,pred))
print("confusion matrix:\n")
print(confusion_matrix(Y_test,pred))

Classification Report:

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        15
          L       0.79      0.91      0.84        74
          R       0.93      0.88      0.90        99

avg / total       0.80      0.82      0.81       188

confusion matrix:

[[ 0 11  4]
 [ 4 67  3]
 [ 5  7 87]]


In [14]:
model1 = DecisionTreeClassifier(criterion='entropy',random_state=3,min_samples_split=15,max_features=2)


In [15]:
model1.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=2, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=15, min_weight_fraction_leaf=0.0,
            presort=False, random_state=3, splitter='best')

In [16]:
pred1 = model1.predict(X_test)


In [17]:
accuracy_score(Y_test,pred1)


0.8138297872340425

In [18]:
print("Classification Report:\n")
print(classification_report(Y_test,pred1))
print("confusion matrix:\n")
print(confusion_matrix(Y_test,pred1))

Classification Report:

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        15
          L       0.83      0.84      0.83        74
          R       0.81      0.92      0.86        99

avg / total       0.75      0.81      0.78       188

confusion matrix:

[[ 0  5 10]
 [ 0 62 12]
 [ 0  8 91]]


C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [19]:
model2 = RandomForestClassifier(random_state=5)


In [20]:
model2.fit(X_train,Y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=5, verbose=0, warm_start=False)

In [21]:
pred2 = model2.predict(X_test)


In [22]:
accuracy_score(Y_test,pred2)


0.851063829787234

In [23]:
print("Classification Report:\n")
print(classification_report(Y_test,pred2))
print("confusion matrix:\n")
print(confusion_matrix(Y_test,pred2))

Classification Report:

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        15
          L       0.84      0.95      0.89        74
          R       0.94      0.91      0.92        99

avg / total       0.83      0.85      0.84       188

confusion matrix:

[[ 0  9  6]
 [ 4 70  0]
 [ 5  4 90]]


In [24]:
model3 = RandomForestClassifier(criterion='entropy',n_jobs=2,max_features=2, min_samples_split=15,random_state=20)

In [25]:
model3.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=15,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=20, verbose=0, warm_start=False)

In [26]:
pred3 = model3.predict(X_test)

In [27]:
accuracy_score(Y_test,pred3)

0.851063829787234

In [28]:
print("Classification Report:\n")
print(classification_report(Y_test,pred3))
print("confusion matrix:\n")
print(confusion_matrix(Y_test,pred3))

Classification Report:

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        15
          L       0.79      0.95      0.86        74
          R       0.91      0.91      0.91        99

avg / total       0.79      0.85      0.82       188

confusion matrix:

[[ 0 10  5]
 [ 0 70  4]
 [ 0  9 90]]


C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
