In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline



In [2]:

from sklearn.datasets import load_digits
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *

In [3]:
data=load_digits()


In [4]:

x=data.data
y=data.target


In [5]:
x=pd.DataFrame(x)
y=pd.DataFrame(y)

In [6]:
x.head()


0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [7]:
x.shape,y.shape


((1797, 64), (1797, 1))

In [8]:
x = preprocessing.scale(x)


In [9]:
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [10]:
x=pd.DataFrame(x)


In [11]:
p = PCA(n_components=16)


In [12]:
p=p.fit_transform(x)
x = p

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)


In [14]:
model= LogisticRegression()


In [15]:
model.fit(X_train,Y_train)


C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
pre = model.predict(X_test)


In [17]:
print("Accuracy Score:\n")
print(metrics.accuracy_score(Y_test,pre)*100)


Accuracy Score:

91.38888888888889


In [18]:
print("Classification Report\n")
print(classification_report(Y_test,pre))


Classification Report

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        38
          1       0.82      0.90      0.86        30
          2       0.90      1.00      0.95        38
          3       0.94      0.84      0.89        37
          4       0.89      0.92      0.90        36
          5       0.94      0.97      0.96        34
          6       0.94      0.88      0.91        33
          7       0.92      0.95      0.94        38
          8       0.97      0.72      0.82        39
          9       0.84      0.97      0.90        37

avg / total       0.92      0.91      0.91       360



In [19]:
print("Confusion Matrix")
print(confusion_matrix(Y_test,pre))

Confusion Matrix
[[38  0  0  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  1  2]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  3 31  0  0  0  2  0  1]
 [ 0  0  0  0 33  0  0  1  0  2]
 [ 0  0  0  0  0 33  0  0  0  1]
 [ 0  2  0  0  2  0 29  0  0  0]
 [ 0  0  0  0  2  0  0 36  0  0]
 [ 0  3  1  2  0  2  2  0 28  1]
 [ 0  1  0  0  0  0  0  0  0 36]]
