In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data

In [3]:
y = data.target

In [4]:
X = pd.DataFrame(X)


In [5]:
y = pd.DataFrame(y)


In [6]:
X.head()


0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [7]:
y.head()


0
0  0
1  0
2  0
3  0
4  0

In [10]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)


In [12]:
y_train.shape


(120, 1)

In [13]:
model = GaussianNB()


In [14]:
model.fit(X_train,y_train.values.reshape(120))


GaussianNB(priors=None)

In [15]:
pre = model.predict(X_test)


In [16]:
model.score(X_test,y_test)*100


96.66666666666667

In [17]:
print(confusion_matrix(y_test,pre))


[[10  0  0]
 [ 0  6  0]
 [ 0  1 13]]


In [18]:
print(classification_report(y_test,pre))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.86      1.00      0.92         6
          2       1.00      0.93      0.96        14

avg / total       0.97      0.97      0.97        30



In [19]:
from sklearn.naive_bayes import MultinomialNB


In [20]:
model1 = MultinomialNB()
model1.fit(X_train,y_train)

C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
pre1 = model1.predict(X_test)


In [22]:
model1.score(X_test,y_test)*100


53.333333333333336

In [23]:
print(confusion_matrix(y_test,pre1))


[[10  0  0]
 [ 0  6  0]
 [ 0 14  0]]


In [24]:
print(classification_report(y_test,pre))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.86      1.00      0.92         6
          2       1.00      0.93      0.96        14

avg / total       0.97      0.97      0.97        30



## question 1


In [25]:
A=9/14
##P(y)
B=5/14  
###P(sunny)
C=3/9 
###P(sunny|y)
P=(C*A)/B

In [27]:
P


0.6