In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [3]:
data=load_digits()


In [4]:
x=data.data


In [5]:
y=data.target


In [6]:
x=pd.DataFrame(x)


In [7]:
y=pd.DataFrame(y)


In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)


In [9]:
Y_train.shape


(1437, 1)

In [10]:
svc1 = SVC(kernel="linear",gamma=20)


In [11]:
svc1.fit(X_train,Y_train.values.reshape(1437))


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=20, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
pred1 =svc1.predict(X_test)


In [13]:
accuracy_score(Y_test,pred1)


0.9833333333333333

In [14]:
print(classification_report(Y_test,pred1))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        40
          1       0.91      0.97      0.94        33
          2       1.00      1.00      1.00        33
          3       0.97      1.00      0.99        37
          4       1.00      1.00      1.00        33
          5       1.00      1.00      1.00        27
          6       0.98      0.98      0.98        43
          7       1.00      1.00      1.00        36
          8       0.97      0.90      0.94        40
          9       1.00      1.00      1.00        38

avg / total       0.98      0.98      0.98       360



In [15]:
print(confusion_matrix(Y_test,pred1))


[[40  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  1  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 37  0  0  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  0  0]
 [ 0  1  0  0  0  0 42  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0]
 [ 0  2  0  1  0  0  1  0 36  0]
 [ 0  0  0  0  0  0  0  0  0 38]]


In [16]:
svc2 = SVC(kernel="poly")


In [17]:
svc2.fit(X_train,Y_train.values.reshape(1437))


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
pred2 =svc2.predict(X_test)


In [19]:
accuracy_score(Y_test,pred2)


0.9916666666666667

In [20]:
print(classification_report(Y_test,pred2))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        40
          1       0.94      1.00      0.97        33
          2       1.00      1.00      1.00        33
          3       1.00      1.00      1.00        37
          4       1.00      1.00      1.00        33
          5       1.00      1.00      1.00        27
          6       0.98      0.98      0.98        43
          7       1.00      1.00      1.00        36
          8       1.00      0.95      0.97        40
          9       1.00      1.00      1.00        38

avg / total       0.99      0.99      0.99       360



In [21]:
print(confusion_matrix(Y_test,pred2))


[[40  0  0  0  0  0  0  0  0  0]
 [ 0 33  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 37  0  0  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  0  0]
 [ 0  1  0  0  0  0 42  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0]
 [ 0  1  0  0  0  0  1  0 38  0]
 [ 0  0  0  0  0  0  0  0  0 38]]


In [22]:
svc3 = SVC(kernel="rbf")


In [23]:
svc3.fit(X_train,Y_train.values.reshape(1437))


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
pred3 =svc3.predict(X_test)


In [25]:
accuracy_score(Y_test,pred3)


0.38055555555555554

In [26]:
print(classification_report(Y_test,pred3))


             precision    recall  f1-score   support

          0       1.00      0.50      0.67        40
          1       1.00      0.48      0.65        33
          2       1.00      0.21      0.35        33
          3       1.00      0.38      0.55        37
          4       1.00      0.45      0.62        33
          5       0.11      1.00      0.19        27
          6       1.00      0.35      0.52        43
          7       1.00      0.39      0.56        36
          8       1.00      0.05      0.10        40
          9       1.00      0.18      0.31        38

avg / total       0.93      0.38      0.46       360



In [27]:
print(confusion_matrix(Y_test,pred3))


[[20  0  0  0  0 20  0  0  0  0]
 [ 0 16  0  0  0 17  0  0  0  0]
 [ 0  0  7  0  0 26  0  0  0  0]
 [ 0  0  0 14  0 23  0  0  0  0]
 [ 0  0  0  0 15 18  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  0  0]
 [ 0  0  0  0  0 28 15  0  0  0]
 [ 0  0  0  0  0 22  0 14  0  0]
 [ 0  0  0  0  0 38  0  0  2  0]
 [ 0  0  0  0  0 31  0  0  0  7]]


In [28]:
svc4 = SVC(kernel="sigmoid")


In [29]:
svc4.fit(X_train,Y_train.values.reshape(1437))


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
pred4 =svc4.predict(X_test)


In [31]:
accuracy_score(Y_test,pred4)


0.075

In [32]:
print(classification_report(Y_test,pred4))


             precision    recall  f1-score   support

          0       0.00      0.00      0.00        40
          1       0.00      0.00      0.00        33
          2       0.00      0.00      0.00        33
          3       0.00      0.00      0.00        37
          4       0.00      0.00      0.00        33
          5       0.07      1.00      0.14        27
          6       0.00      0.00      0.00        43
          7       0.00      0.00      0.00        36
          8       0.00      0.00      0.00        40
          9       0.00      0.00      0.00        38

avg / total       0.01      0.07      0.01       360



C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
print(confusion_matrix(Y_test,pred4))


[[ 0  0  0  0  0 40  0  0  0  0]
 [ 0  0  0  0  0 33  0  0  0  0]
 [ 0  0  0  0  0 33  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  0  0  0  0 33  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  0  0]
 [ 0  0  0  0  0 43  0  0  0  0]
 [ 0  0  0  0  0 36  0  0  0  0]
 [ 0  0  0  0  0 40  0  0  0  0]
 [ 0  0  0  0  0 38  0  0  0  0]]
