## question 1

In [5]:
import numpy as np

In [12]:
a=np.random.random([10,1])


In [13]:
a

array([[0.91160167],
       [0.63952776],
       [0.80027552],
       [0.15534565],
       [0.89231892],
       [0.26105083],
       [0.49598687],
       [0.95972262],
       [0.53569201],
       [0.10826229]])

In [18]:
np.mean(a)

0.5759784146951009

## question 2


In [19]:
b=np.random.random([20,1])

In [20]:
b

array([[0.82324408],
       [0.78155964],
       [0.38123189],
       [0.64828384],
       [0.27933754],
       [0.72603926],
       [0.56366143],
       [0.21496006],
       [0.32398324],
       [0.47147558],
       [0.38321997],
       [0.0800128 ],
       [0.65211835],
       [0.56902828],
       [0.56387693],
       [0.65632723],
       [0.72916873],
       [0.29338187],
       [0.81245714],
       [0.40796317]])

In [22]:
np.var(b)

0.04389850336214498

In [24]:
np.std(b)

0.20951969683575092

## question 3

In [26]:
c=np.random.random([10,20])

In [27]:
d=np.random.random([20,25])

In [29]:
e=np.dot(c,d)

In [30]:
e

array([[4.5609723 , 4.87359688, 5.12777662, 4.09842758, 3.56926994,
        4.44944053, 5.54623349, 6.54463554, 4.31267245, 5.75460263,
        3.92964804, 4.19549529, 5.47875409, 5.37781214, 5.28653773,
        4.70780611, 3.5375922 , 5.04032449, 3.58059361, 5.28733744,
        5.71524495, 3.65605653, 6.1506986 , 4.46440321, 5.53296337],
       [5.02005347, 5.1603507 , 5.73799966, 5.02929172, 4.00793412,
        5.17270812, 4.96227324, 7.00918353, 4.8222737 , 6.07346462,
        4.76829659, 4.81044242, 5.32955789, 6.42330803, 4.97386151,
        5.49227564, 4.43039587, 4.94560248, 4.13664173, 5.37430706,
        5.65694966, 3.86926448, 6.41683219, 5.18733316, 5.69911918],
       [2.87411687, 3.84325449, 3.85310197, 3.26661288, 2.37135036,
        3.37588509, 4.09561374, 5.38923833, 4.70344238, 5.01055725,
        3.90570544, 3.43676078, 4.81419641, 5.07328686, 3.53227423,
        3.22317628, 2.89031194, 4.8447867 , 2.22296898, 4.67105045,
        4.09901628, 3.2321217 , 4.77802925, 2.

In [31]:
e.shape

(10L, 25L)

In [33]:
np.sum(e)
      

1274.874860188405

## question 4

In [8]:
import numpy as np

In [9]:
w = np.arange(10).reshape(10,1)

In [10]:
def myfunc(x,axis):
    return 1/(1+ np.exp(-x))

In [11]:
np.apply_over_axes(myfunc,w,1)

array([[0.5       ],
       [0.73105858],
       [0.88079708],
       [0.95257413],
       [0.98201379],
       [0.99330715],
       [0.99752738],
       [0.99908895],
       [0.99966465],
       [0.99987661]])